/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arihant_ims;

/**
 *
 * @author admin
 */
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class Customers extends javax.swing.JDialog {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    String click = "";
    String PaneLabel = "";
    String editItem = "";

    /**
     * Creates new form RawMaterials
     */
    public Customers(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        conn = CreateConnection.connectDB();
        initComponents();
        Dimension scrn = getToolkit().getScreenSize();
        this.setBounds(0, 0, scrn.width, scrn.height);
        Table.setSelectionForeground(Color.red);
        Table.setRowHeight(25);
        try {

            /*
             * String sq = "insert into RawMaterials values(?,?,?,?)";
             *
             * pst = conn.prepareStatement(sq); pst.setString(1,"tom");
             * pst.setString(2, "6"); pst.setString(3, "67"); pst.setString(4,
             * "46"); pst.addBatch(); pst.executeBatch();
             *
             *
             *
             */

            fill_table();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (SQLException ex) {
            }


        }
    }

    private void fill_table() {
        try {
            pst = conn.prepareStatement("select name as 'Customer Name',number as 'Contact no.',address as 'Address',email as 'Email-id',narration as 'Narration' from Customers order by name");
            rs = pst.executeQuery();
            Table.setModel(C.getModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception ex) {
            }


        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ButtonAdd = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        TextNumber = new javax.swing.JTextField();
        TextAddress = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaNarration = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customers");
        setBackground(new java.awt.Color(255, 51, 204));
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        TextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSearchActionPerformed(evt);
            }
        });
        TextSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextSearch)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTROLS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        ButtonAdd.setText("<html><h2>ADD NEW CUSTOMER");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });
        ButtonAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonAddKeyPressed(evt);
            }
        });

        ButtonEdit.setText("<html><h2>EDIT DETAILS ");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });
        ButtonEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonEditKeyPressed(evt);
            }
        });

        ButtonDelete.setText("<html><h2>DELETE");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        ButtonDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonDeleteKeyPressed(evt);
            }
        });

        ButtonClear.setText("<html><h2>CLEAR");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });
        ButtonClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonClearKeyPressed(evt);
            }
        });

        ButtonRefresh.setText("<html><h2>REFRESH");
        ButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshActionPerformed(evt);
            }
        });
        ButtonRefresh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonRefreshKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ButtonEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonRefresh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMERS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        jLabel1.setText("<html><h2>Contact number");

        jLabel2.setText("<html><h2>Address");

        jLabel3.setText("<html><h2>Customer Name");

        jLabel4.setText("<html><h2>Narration");

        TextName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextName.setForeground(new java.awt.Color(0, 0, 204));
        TextName.setEnabled(false);
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });
        TextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNameKeyPressed(evt);
            }
        });

        TextNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextNumber.setEnabled(false);
        TextNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNumberKeyPressed(evt);
            }
        });

        TextAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextAddress.setEnabled(false);
        TextAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextAddressKeyPressed(evt);
            }
        });

        TextEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TextEmail.setEnabled(false);
        TextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextEmailKeyPressed(evt);
            }
        });

        jLabel5.setText("<html><h2>Email-id");

        TextAreaNarration.setColumns(20);
        TextAreaNarration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TextAreaNarration.setRows(5);
        TextAreaNarration.setEnabled(false);
        TextAreaNarration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextAreaNarrationKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TextAreaNarration);

        jButton1.setText("<html><h1>SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton6.setText("Clear DB table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(TextAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap())))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(51, 0, 255))); // NOI18N

        Table.setAutoCreateRowSorter(true);
        Table.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setRowMargin(2);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButton2.setText("<html><h1>HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSearchActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row_num = Table.getSelectedRow();
        String row_id = Table.getModel().getValueAt(row_num, 0).toString();
        String sql = "select * from Customers where name='" + row_id + "'";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                TextName.setText(rs.getString("name"));
                TextNumber.setText(rs.getString("number"));
                TextAddress.setText(rs.getString("address"));
                TextEmail.setText(rs.getString("email"));
                TextAreaNarration.setText(rs.getString("narration"));
                click = "readyForEdit";
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (SQLException ex) {
            }


        }
        TextName.setEnabled(false);
        TextNumber.setEnabled(false);
        TextAddress.setEnabled(false);
        TextEmail.setEnabled(false);

    }//GEN-LAST:event_TableMouseClicked

    private void TextSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextSearchKeyReleased
        try {
            pst = conn.prepareStatement("select * from Customers where name='" + TextSearch.getText() + "' COLLATE NOCASE");
            rs = pst.executeQuery();

            if (rs.next()) {
                TextName.setText(rs.getString("name"));
                TextNumber.setText(rs.getString("number"));
                TextAddress.setText(rs.getString("address"));
                TextEmail.setText(rs.getString("email"));
                TextAreaNarration.setText(rs.getString("narration"));
                click = "readyForEdit";
            } else {
                TextName.setText("");
                TextNumber.setText("");
                TextAddress.setText("");
                TextEmail.setText("");
                TextAreaNarration.setText("");
                click = "";
            }

        } catch (Exception e) {
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (SQLException ex) {
            }


        }
        TextName.setEnabled(false);
        TextNumber.setEnabled(false);
        TextAddress.setEnabled(false);
        TextEmail.setEnabled(false);  
        TextAreaNarration.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_TextSearchKeyReleased

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        TextName.setText("");
        TextNumber.setText("");
        TextAddress.setText("");
        TextEmail.setText("");
        TextAreaNarration.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        TextName.grabFocus();
        TextName.setText("");
        TextNumber.setText("");
        TextAddress.setText("");
        TextEmail.setText("");
        TextAreaNarration.setText("");
        TextName.setEnabled(true);
        TextNumber.setEnabled(true);
        TextAddress.setEnabled(true);
        TextEmail.setEnabled(true);
        TextAreaNarration.setEnabled(true);
        click = "add";
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        if (click.equals("readyForEdit")) {
            TextName.setEnabled(true);
            TextNumber.setEnabled(true);
            TextAddress.setEnabled(true);
            TextEmail.setEnabled(true);
            TextAreaNarration.setEnabled(true);
            click = "edit";
            editItem = TextName.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Please Select an item to edit from search box or table");
        }

    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed

         if (click.equals("readyForEdit")) {
            int i = JOptionPane.showConfirmDialog(null, "Are you sure", "Delete Confirmation", 0);
            // System.out.print(i);
            if (i == 0) {
                click = "";

                String sql = "delete from Customers where name='" + TextName.getText() + "'";
                try {
                    // TODO add your handling code here:

                    pst = conn.prepareStatement(sql);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "item deleted");
                } catch (SQLException ex) {
                    Logger.getLogger(RawMaterials1.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        pst.close();
                        rs.close();
                    } catch (Exception e) {
                    }
                }

                // fill_table();
                //onAddButtonClick();
                //disableAll();
            }
        } else if (click.equals("edit")) {
            JOptionPane.showMessageDialog(null, "The item is still in editing mode.");
        } else {
            JOptionPane.showMessageDialog(null, "Please Select an item to delete from search box or table");
        }

        
        
        
        
        
        /*        if (click.equals("readyForEdit")) {


            String sql = "delete from Customers where name='" + TextName.getText() + "'";
            DialogDelete.SqlDel = sql;
            DialogDelete.main(null);
        }else if(click.equals("edit")){
        JOptionPane.showMessageDialog(null, "The item is still in editing mode.");
        } 
        else {
            JOptionPane.showMessageDialog(null, "Please Select an item to delete from search box or table");
        }
        * 
        */
// TODO add your handling code here:

    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshActionPerformed
        try {
            fill_table();        // TODO add your handling code here:
        } catch (Exception e) {
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (SQLException ex) {
            }


        }
        TextName.setEnabled(false);
        TextName.setText("");
        TextNumber.setEnabled(false);
        TextNumber.setText("");
        TextAddress.setEnabled(false);
        TextAddress.setText("");
        TextEmail.setEnabled(false);
        TextEmail.setText("");
        TextAreaNarration.setEnabled(false);
        TextAreaNarration.setText("");
    }//GEN-LAST:event_ButtonRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PaneLabel="";
        if (click.equals("edit")) {
            if (TextName.isEnabled() == true && TextNumber.isEnabled() == true && TextAddress.isEnabled() == true && TextEmail.isEnabled() == true) {
                if (TextName.getText().equals("")) {
                    PaneLabel = "Customer Name";
                }
                /*
                if (TextNumber.getText().equals("")) {
                    PaneLabel = "";
                }
                if (TextAddress.getText().equals("")) {
                    PaneLabel = "Item Reorder quantity";
                }
                if (TextEmail.getText().equals("")) {
                    PaneLabel = "Item Opening Stock";
                }
                * 
                */
                if (PaneLabel.equals("")) {
                    String sql = "Update Customers set name='" + TextName.getText() + "',number='" + TextNumber.getText() + "',address='" + TextAddress.getText() + "',email='" + TextEmail.getText()+ "',narration='" + TextAreaNarration.getText() + "' where name='" + editItem + "'";
                    try {
                        Statement stm = conn.createStatement();
                        //pst = conn.prepareStatement(sql);
                     /*
                         * pst.setString(1, TextName.getText());
                         * pst.setString(2, TextCost.getText());
                         * pst.setString(3, TextReorder.getText());
                         * pst.setString(4, TextOpening.getText());
                         * pst.setString(5, TextName.getText()); pst.addBatch();
                         * pst.executeBatch();
                         *
                         */
                        stm.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Record Updated ");
                        ButtonRefresh.doClick();
                        click="";
                        TextName.setEnabled(false);
                        TextName.setText("");
                        TextNumber.setEnabled(false);
                        TextNumber.setText("");
                        TextAddress.setEnabled(false);
                        TextAddress.setText("");
                        TextEmail.setEnabled(false);
                        TextEmail.setText("");
                        TextAreaNarration.setText("");
                        TextAreaNarration.setEnabled(false);

                    } catch (SQLException ex) {
                        Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Error occured: Duplicate value for party name");
                    } finally {
                        try {
                            pst.close();
                            rs.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Enter value for " + PaneLabel);
                }
            }
        } else if (click.equals("add")) {
            if (TextName.isEnabled() == true && TextNumber.isEnabled() == true && TextAddress.isEnabled() == true && TextEmail.isEnabled() == true) {
                if (TextName.getText().equals("")) {
                    PaneLabel = "Customer Name";
                }
                /*
                if (TextNumber.getText().equals("")) {
                    PaneLabel = "Item Cost";
                }
                if (TextAddress.getText().equals("")) {
                    PaneLabel = "Item Reorder quantity";
                }
                if (TextEmail.getText().equals("")) {
                    PaneLabel = "Item Opening Stock";
                }
                * 
                */
                if (PaneLabel.equals("")) {
                    String sql = "Insert into Customers values( '" + TextName.getText() + "','" + TextNumber.getText() + "','" + TextAddress.getText() + "','" + TextEmail.getText() + "','" +TextAreaNarration.getText()+"')";
                    try {
                        Statement stm = conn.createStatement();
                        //pst = conn.prepareStatement(sql);
                     /*
                         * pst.setString(1, TextName.getText());
                         * pst.setString(2, TextCost.getText());
                         * pst.setString(3, TextReorder.getText());
                         * pst.setString(4, TextOpening.getText());
                         * pst.setString(5, TextName.getText()); pst.addBatch();
                         * pst.executeBatch();
                         *
                         */
                        stm.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Record Added ");
                        ButtonRefresh.doClick();
                        TextName.setEnabled(false);
                        TextName.setText("");
                        TextNumber.setEnabled(false);
                        TextNumber.setText("");
                        TextAddress.setEnabled(false);
                        TextAddress.setText("");
                        TextEmail.setEnabled(false);
                        TextEmail.setText("");
                         TextAreaNarration.setText("");
                        TextAreaNarration.setEnabled(false);

                    } catch (SQLException ex) {
                        Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Error occured: Duplicate value for party name");
                    } finally {
                        try {
                            pst.close();
                            rs.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Enter value for " + PaneLabel);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}     
 else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void ButtonAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonAddKeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}     
else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }
    }//GEN-LAST:event_ButtonAddKeyPressed

    private void ButtonEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonEditKeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditKeyPressed

    private void ButtonDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonDeleteKeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}    else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteKeyPressed

    private void ButtonClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonClearKeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
} else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_ButtonClearKeyPressed

    private void ButtonRefreshKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonRefreshKeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}  else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRefreshKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
int a=evt.getKeyCode();
if(a==10){
            try {
                Robot robot= new Robot();
                robot.keyPress(KeyEvent.VK_SPACE);
                robot.keyRelease(KeyEvent.VK_SPACE);
            } catch (AWTException ex) {
                Logger.getLogger(OutTransaction.class.getName()).log(Level.SEVERE, null, ex);
            }
}  else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }            // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  CreateConnection.DeleteAll("Customers", conn);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TextAreaNarrationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAreaNarrationKeyPressed
       int a=evt.getKeyCode(); 
     if(a==9){
     jButton1.grabFocus();
     }else if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }
    }//GEN-LAST:event_TextAreaNarrationKeyPressed

    private void TextSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextSearchKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TextSearchKeyPressed

    private void TextNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNameKeyPressed
      int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_TextNameKeyPressed

    private void TextNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNumberKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumberKeyPressed

    private void TextAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAddressKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TextAddressKeyPressed

    private void TextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEmailKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailKeyPressed

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3KeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2KeyPressed

    private void TableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TableKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
int a=evt.getKeyCode();
if(a==27){
            jButton2.doClick();
        }
        
        else if(a == 113){
            jButton1.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Customers dialog = new Customers(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonRefresh;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextArea TextAreaNarration;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextNumber;
    private javax.swing.JTextField TextSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
