/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * production_delete.java
 *
 * Created on Mar 9, 2013, 3:19:15 PM
 */

package arihant_ims;

import java.awt.Dimension;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author Naman
 */
public class production_delete extends javax.swing.JDialog {
   Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    public production_delete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    conn = CreateConnection.connectDB();
        initComponents();
        Dimension scrn = getToolkit().getScreenSize();
        this.setBounds(0, 0, scrn.width, scrn.height);
        Table.setRowHeight(25);
        try {

    

            fill_table();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (SQLException ex) {
            }


        }
    }

    private void fill_table() {
        try {
            System.out.println("filler");
            pst = conn.prepareStatement("select * from Production");
            rs = pst.executeQuery();
            System.out.println(rs);
            Table.setModel(C.getModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(RawMaterials.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception ex) {
            }


        }

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Table.setAutoCreateRowSorter(true);
        Table.setFont(new java.awt.Font("Times New Roman", 0, 18));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setColumnSelectionAllowed(true);
        Table.setRowMargin(2);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
//        int row_num = Table.getSelectedRow();
//        String row_id = Table.getModel().getValueAt(row_num, 0).toString();
//        String sql = "select * from RawMaterials where itemName='" + row_id + "'";
//        try {
//            pst = conn.prepareStatement(sql);
//            rs = pst.executeQuery();
//            if (rs.next()) {
//                TextName.setText(rs.getString("itemName"));
//                TextAlias.setText(rs.getString("itemAlias"));
//                TextCost.setText(rs.getString("cost"));
//                TextReorder.setText(rs.getString("reorder"));
//                TextOpening.setText(rs.getString("initialStock"));
//                //TextNarration.setText(rs.getString("narration"));
//                currentStock = Double.parseDouble(rs.getString("openingStock"));
//                click = "readyForEdit";
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(RawMaterials.class.getName()).log(Level.SEVERE, null, ex);
//        } finally {
//            try {
//                pst.close();
//                rs.close();
//            } catch (SQLException ex) {
//            }
//
//
//        }
//        TextName.setEnabled(false);
//        TextCost.setEnabled(false);
//        TextReorder.setEnabled(false);
//        TextOpening.setEnabled(false);
//        TextAlias.setEnabled(false);
//        TextNarration.setEnabled(false);
    }//GEN-LAST:event_TableMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                production_delete dialog = new production_delete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
